//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemTra_Lan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaMua
    {
        public Nullable<int> ID { get; set; }
        public string MSP { get; set; }
        public string TrangThai { get; set; }
        public string SoLuongDaMua { get; set; }
        public string MaVoucher { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<System.DateTime> ThoiGianHienTai { get; set; }
        public int MaVanChuyen { get; set; }
        public Nullable<System.DateTime> ThoiGianDat { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
