//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemTra_Lan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChiGiaoHang
    {
        public Nullable<int> IDNguoiMua { get; set; }
        public string MSP { get; set; }
        public string HoTen { get; set; }
        public string soDT { get; set; }
        public string DiaChiNhanHang { get; set; }
        public Nullable<System.DateTime> ThoiGianThayDoi { get; set; }
        public int MaDiaChi { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
