//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemTra_Lan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamHuy
    {
        public Nullable<int> ID { get; set; }
        public string MSP { get; set; }
        public string LyDoHuy { get; set; }
        public Nullable<System.DateTime> ThoiGianHuy { get; set; }
        public int MaHuy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
