//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemTra_Lan2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int ID { get; set; }
        public string MaVoucher { get; set; }
        public string Mota { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
        public Nullable<int> SoLuongVoucher { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
